version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1.29.0

workflows:
  heroku_deploy:
    jobs:
      - node/run
      - cypress/run:
          start: npm start 
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main
          requires:
            - node/run
            - cypress/run    
